# only cmake since 3.13 supports packaging of debuginfo
cmake_minimum_required ( VERSION 3.17 )

set ( CPACK_PACKAGING_INSTALL_PREFIX "/usr" )
set ( CPACK_GENERATOR DEB )
set ( CPACK_DEBIAN_FILE_NAME DEB-DEFAULT )
set ( CPACK_DEB_COMPONENT_INSTALL ON )
set ( CPACK_DEBIAN_DEBUGINFO_PACKAGE ON )
set ( CPACK_DEBIAN_PACKAGE_SECTION misc )
set ( CPACK_DEBIAN_PACKAGE_PRIORITY optional )
set ( CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION ON )
set ( CPACK_DEBIAN_PACKAGE_SUGGESTS "manticore (>= 3.6.1)" )

if (NOT disable_shlideps)
	set ( CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON )
endif ()

set ( CPACK_DEBIAN_COLUMNAR_PACKAGE_NAME "${CPACK_PACKAGE_NAME}" )
set ( CPACK_DEBIAN_COLUMNAR_PACKAGE_DEPENDS "")
set ( CPACK_DEBIAN_COLUMNAR_PACKAGE_SECTION common )

set ( CPACK_DEBIAN_META_PACKAGE_NAME "${CPACK_META_PACKAGE_NAME}" )
set ( CPACK_DEBIAN_META_PACKAGE_DEPENDS "${CPACK_PACKAGE_NAME} (= ${CPACK_PACKAGE_VERSION}), ${CPACK_EXECUTOR_PACKAGE_NAME} (= ${CPACK_EXECUTOR_PACKAGE_VERSION})" )
#set ( CPACK_DEBIAN_META_PACKAGE_ARCHITECTURE all )
set ( CPACK_DEBIAN_META_PACKAGE_DEBUG OFF )
set ( CPACK_DEBIAN_META_PACKAGE_SECTION metapackages )

get_cmake_property ( CPACK_COMPONENTS_ALL COMPONENTS )
list ( APPEND CPACK_COMPONENTS_ALL "columnar" "meta" )
