# only cmake since 3.13 supports packaging of debuginfo
cmake_minimum_required ( VERSION 3.17 )

SET ( CPACK_PACKAGING_INSTALL_PREFIX "/usr" )
set ( CPACK_GENERATOR DEB )

set ( CPACK_DEBIAN_FILE_NAME DEB-DEFAULT )
set ( CPACK_DEB_COMPONENT_INSTALL OFF )
set ( CPACK_DEBIAN_DEBUGINFO_PACKAGE ON )
set ( CPACK_DEBIAN_PACKAGE_SECTION misc )
set ( CPACK_DEBIAN_PACKAGE_PRIORITY optional )
set ( CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION ON )
set ( CPACK_DEBIAN_PACKAGE_SUGGESTS "manticore (>= 3.6.1)" )

if (NOT disable_shlideps)
	set ( CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON )
endif ()